### ISSUE TITLE
How do I authenticate?

### ISSUE THREAD

**Issue by Sweeper777** [zakhardavydov/fitneshren#1]
What are the names of the parameters for the login and password? Can you show a sample authenticate request?

I am using the below code and it doesn't seem to do anything:

    feathers.authenticate([
        "login": "admin", "password": "admin"
    ])

Also, what provider are you using? Rest or Socket.io?

**Comment by Sweeper777** [comment]
Sorry but I could not understand what the link is talking about... I have never used feathers before. I've only sent HTTP GET requests before...

I found the [authentication](https://github.com/feathersjs-ecosystem/feathers-swift#authentication) section of the feathers-swift library that I am using. Apparently, I need a strategy parameter and an access token? How do I get those?

**Comment by vovayrovsky** [comment]
Heh, I've never used feathers before too... Ok.
Well, you should get some information about user you want to authenticate to the feathers app. In our case  you should use something like this: 
feathersRestApp.authenticate([
  "strategy": "local",
  "email": "admin",
  "password": "admin"
])
.start();

So, strategy means which type of authentication you are using, email and password fields are login and password fields.

You can use feathersjs docs to better understanding Feathers ideology (or something like this ;-) ): 
https://docs.feathersjs.com/

**Comment by Sweeper777** [comment]
I've managed to get it to log some stuff out. And apparently there is a "Not Found" error. I suspect I might have used the wrong URL. Is the URL "https://ilich.ml/" the correct URL to use if I want to connect to the test server?
